# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 02:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtemp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='caption_1',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='room',
            name='caption_2',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='room',
            name='caption_3',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='room',
            name='caption_4',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='room',
            name='feed',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='room',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, choices=[('b', 'Binary Room'), ('q', 'Quad Room'), ('t', 'Thermometer'), ('n', 'Needle')], default='t', help_text='Room type', max_length=1),
        ),
        migrations.AddField(
            model_name='room',
            name='vote_interval',
            field=models.DurationField(default=datetime.timedelta(0, 60)),
        ),
    ]
