# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rtemp', '0003_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.CharField(default='', max_length=300)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtemp.Room')),
            ],
        ),
    ]
