# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtemp', '0004_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.CharField(default='', max_length=8),
        ),
    ]
