# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtemp', '0006_auto_20170428_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='attendee',
            field=models.ForeignKey(default='9', on_delete=django.db.models.deletion.CASCADE, to='rtemp.Attendee'),
        ),
    ]
