# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtemp', '0007_vote_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='thumbs',
            field=models.CharField(blank=True, choices=[('+', 'Thumbs Up'), ('-', 'Thumbs Down')], help_text='Thumbs up/down', max_length=1),
        ),
    ]
